### ISSUE TITLE
unknown command 'spacing_left' for domain 'config'

### ISSUE THREAD

**Issue by joytianya** [cmacrae/spacebar#42]
/usr/local/var/log/spacebar/spacebar.err.log
unknown command 'spacing_left' for domain 'config'
unknown command 'spacing_right' for domain 'config'
why?

**Comment by jraregris** [comment]
I think that is because the spacing stuff is not released yet. The Readme-file in the repo is whatever the opposite of _outdated_ is.

You can see the Readme for the currently latest release (`v1.1.1`) here https://github.com/cmacrae/spacebar/blob/b075de54d67a0bf7ba5b4433d3304de7f9ea8dd9/README.md

@cmacrae: It would be nice with another release soon!

**Comment by cmacrae** [comment]
Thanks for bringing this to my attention, and thanks for chiming in here @jraregris 🙌   
I'll do a release now :)

**Comment by cmacrae** [comment]
This should be fixed in v1.2.0, which I just released :) I have no means of testing the Homebrew formula right now, so give it a go and let me know if it looks resolved

**Comment by joytianya** [comment]
thank you ! I upgrade spacebar and solve it , no "unknown command spacing_left ..." error in log
