### ISSUE TITLE
Error: running as root

### ISSUE THREAD

**Issue by andynameistaken** [cmacrae/spacebar#53]
When running `spacebar` as brew service bar does not appear and output of
`/usr/local/var/log/spacebar/spacebar.err.log` is
`spacebar: running as root is not allowed! abort..`

On the other hand running it directly from terminal is fine.

**Comment by cmacrae** [comment]
Hey @andynameistaken 👋 Hmm, that's strange - I haven't seen anyone else report this issue.  
Could you please detail your setup? How you installed spacebar and how you run it?

**Comment by andynameistaken** [comment]
oh sorry, I got another computer and it works now and I couldn't replicate what happened. Anyway as this post is question I wanted to ask about:

- are you planning adding mouse support for changing workspaces?
- is it posible to write plugins to this bar (like with Polybar for example)?

**Comment by cmacrae** [comment]
No need for apologies @andynameistaken!  

>are you planning adding mouse support for changing workspaces?

Mouse support is certainly on the radar. I'm at the beginning of a complete rewrite from scratch and this is one of the features I'll be looking to accommodate.  

>is it posible to write plugins to this bar (like with Polybar for example)?

As for plugins, yes that's possible. There's a collection of unreleased features on the `master` branch that allow custom output to be displayed at the left, centre, and right of the bar by way of shell pipelines. In the rewritten version, this won't be limited to just one slot per section :)

**Comment by cmacrae** [comment]
I just released 1.3.0 :) That has the shell features

**Comment by andynameistaken** [comment]
Nice!  BTW, it would be cool to set font size per item  - in Font Awesome 'clock' and 'bolt' are different size and making one bigger or other smaller, also option for PowerLine glyphs for workspaces is nice idea. 

Anyway, thanks for this project it is the best bar for macOS I tried - it has small resources footprint and works with workspaces OOTB. Please consider adding link for donations :)

**Comment by cmacrae** [comment]
Thanks for the input 🙇   
The rewrite already has support for differing font size (and just fonts in general) per module :) So, hang tight!

As for the 'PowerLine glyphs', perhaps you could elaborate?

Thanks for the kind words! I'm glad you're enjoying it! I'll certainly consider adding a donations link, that's very thoughtful of you to mention :)

**Comment by cmacrae** [comment]
Oh! I should mention, if you want to raise ideas for discussion, you can always start a thread over [in the discussions](https://github.com/cmacrae/spacebar/discussions) :)

**Comment by LachlanMarnham** [comment]
I also hit this issue and couldn't work out what was going on. Running `spacebar` from the terminal worked just fine, but it would fail with the error message `running as root is not allowed!` when trying to orchestrate with `brew services start spacebar`. I did not fix the issue, but I found a workaround which may be useful to anybody else that encounters the same problem in the future. This also relates to #89.

1. Using the instructions [here](https://superuser.com/questions/229773/run-command-on-startup-login-mac-os-x), use automator to create a shell script which will run automatically on startup.
2. By reference the contents of `homebrew.mxcl.spacebar.plist`, I used the following shell script for mine:
```
PATH=/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
/opt/homebrew/opt/spacebar/bin/spacebar >/dev/null 2>&1 &
```
Note that this will send stdout and stderr to `/dev/null` instead of the log files defined in `homebrew.mxcl.spacebar.plist`. I tried using the proper log files, but it caused the script to fails for reasons I don't understand.
3. Follow the remaining steps in (1) to register the script to run on startup. You will need to grant it accessibility permissions the first time it runs.

**Comment by scbizu** [comment]
Here are some tips who encounters this issue: 

* Try to clean up the spacebar daemon startup with root user:

```shell 
sudo brew services stop spacebar
sudo brew services cleanup  
```

* Restart the spacebar daemon:

```shell
brew services restart spacebar
```
