### ISSUE TITLE
Updated Release?

### ISSUE THREAD

**Issue by booherbg** [cmacrae/spacebar#6]
My version (installed via brew) doesn't support the new clock format. Any chance we could get an updated release :)

I don't believe I have an updated XCode environment on this laptop otherwise I could try to rebuild myself.

**Comment by yanzhang0219** [comment]
Install it from --HEAD (you should codesign it). You can refer to [Installing yabai (from HEAD)](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#updating-to-latest-head). Install spacebar from HEAD has the same procedure.

**Comment by yangnom** [comment]
I'm trying to reinstall from --HEAD by following with the yabai --HEAD installation but when I get to the codesigning part

```
codesign -fs "${SPACEBAR_CERT:-spacebar-cert}" "$(brew --prefix spacebar)/bin/spacebar"
```
I get the error
```
spacebar-cert: no identity found
```

I know I'm definitely doing something very dumb here as I'm mostly just copying and pasting the yabai stuff into terminal and replacing anything that has `yabai` with `spacebar`

Any help would be great here as I'm unfamiliar with codesigning and I imagine other people will end up with this problem because one of the recommended forms of installation is through homebrew.

**Comment by yanzhang0219** [comment]
First, create a separate certificate for spacebar referring to https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD):

> First, open Keychain Access.app. In its menu, navigate to Keychain Access, then Certificate Assistance, then click Create a Certificate.... This will open the Certificate Assistant. Choose these options:
> 
> * Name: spacebar-cert,
> * Identity Type: Self-Signed Root
> * Certificate Type: Code Signing
>
> Click Create, then Continue to create the certificate.

If you don't have spacebar in your device:
```bash
brew install somdoron/formulae/spacebar --HEAD
codesign -fs 'spacebar-cer' $(which spacebar)
```

To upgrade spacebar:
```bash
# stop spacebar service
brew services stop somdoron/formulae/spacebar

# reinstall spacebar
brew reinstall somdoron/formulae/spacebar
codesign -fs "spacebar-cert" "$(brew --prefix spacebar)/bin/spacebar"

# start spacebar service
brew services start somdoron/formulae/spacebar
```

**Comment by cmacrae** [comment]
I've now inherited spacebar and will actively be working on maintaining and developing it, including new releases :)  
I'm going to close this issue off, as you should start seeing more frequent releases
